# Generated by Django 4.2.5 on 2023-10-01 16:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=30, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("premium", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-date_added",),
                "abstract": False,
            },
        ),
    ]
