# Generated by Django 4.2.5 on 2023-09-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("premium", models.BooleanField(default=False)),
            ],
        ),
    ]
