# Generated by Django 4.2.5 on 2023-10-01 16:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPost",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=100)),
                ("game_link", models.URLField(blank=True, max_length=60, null=True)),
                ("body", models.TextField()),
            ],
            options={
                "ordering": ("-date_added",),
                "abstract": False,
            },
        ),
    ]
