# Generated by Django 4.2.5 on 2023-09-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpost",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
