# Generated by Django 4.2.5 on 2023-10-02 20:07

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpost",
            name="game_link",
            field=models.URLField(
                blank=True, max_length=60, null=True, validators=[core.validators.validate_chess_game_url]
            ),
        ),
    ]
