# Generated by Django 4.2.5 on 2023-10-08 15:05

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import posts.models.post


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_userpost_game_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=posts.models.post.user_post_image_upload_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='posts.userpost')),
            ],
        ),
    ]
