# Generated by Django 4.2.5 on 2023-09-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-date_added',)},
        ),
    ]
