[tool.isort]
line_length = 120
known_third_party = ["django", "celery", "redis"]

[tool.mypy]
python_version = 3.10
plugins = ["mypy_django_plugin.main"]
follow_imports = normal
follow_imports_for_stubs = true
disallow_untyped_defs = True
check_untyped_defs = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = True
ignore_missing_imports = True

[mypy.plugins.django-stubs]
django_settings_module = "src.config.settings.dev"

[tool.flake8]
config = "flake8.cfg"

[tool.black]
config = "black.toml"





